routes/web.php
<?php

use App\Http\Controllers\CommentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('website.welcome');
})->name('welcome');


Auth::routes();

Route::get('/home', function () {
    return view('website.welcome');
})->name('home');

Route::resource('categories', App\Http\Controllers\CategoryController::class);
Route::get('categories/{category}/posts', [App\Http\Controllers\PostController::class, 'index'])->name('categories.posts.index');
Route::resource('donations', App\Http\Controllers\DonationController::class);
Route::get('posts/get-more-posts', [App\Http\Controllers\PostController::class, 'getMorePosts'])->name('get-more-posts');
Route::resource('posts', App\Http\Controllers\PostController::class);
Route::resource('posts/{post}/comments', CommentController::class);
Route::post('posts/storeimage', [App\Http\Controllers\PostController::class, 'storeImage'])->name('store.image');
Route::resource('subscribers', App\Http\Controllers\SuscriberController::class);
Route::resource('volunteers', App\Http\Controllers\VolunteerController::class);

Route::prefix('admin')->name('admin.')->middleware('auth')->group(function () {
    Route::resource('posts', App\Http\Controllers\Admin\PostController::class, [
        'except' => ['create', 'store']
    ]);

    Route::resource('subscribers', App\Http\Controllers\Admin\SubscriberController::class, [
        'except' => ['create', 'store']
    ]);

    Route::delete('subscribers/{subscriber?}', [\App\Http\Controllers\Admin\SubscriberController::class, 'destroy'])->name('subscribers.destroy');



    Route::resource('volunteers', App\Http\Controllers\Admin\VolunteerController::class, [
        'except' => ['create', 'store']
    ]);

    Route::resource('comments', App\Http\Controllers\Admin\CommentController::class, [
        'except' => ['create', 'store']
    ]);

    Route::resource('donations', App\Http\Controllers\Admin\DonationController::class, [
        'except' => ['create', 'store', 'destroy']
    ]);

    Route::resource('categories', App\Http\Controllers\Admin\CategoryController::class);

    Route::get('posts/{post}/approved', [App\Http\Controllers\Admin\PostApprovalController::class, 'publish'])->name('posts.publish');

    Route::patch('volunteers/{volunteer}/approve', [App\Http\Controllers\Admin\VolunteerApprovalController::class, 'approve'])->name('volunteers.approve');
    Route::patch('volunteers/{volunteer}/reject', [App\Http\Controllers\Admin\VolunteerApprovalController::class, 'reject'])->name('volunteers.reject');
});

app/Models/Volunteer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Volunteer extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'phone_number',
        'birthdate',
        'body',
        'status',
        'reviewed_at'
    ];

    public function scopeByStatus($query, $status)
    {
        switch ($status) {
            case 'all':
                return $query->withTrashed();
            case 'delete':
                return $query->onlyTrashed();
            case 'active':
                return $query->whereNull('deleted_at');
        }
    }
}

app/Http/Controllers/API/VolunteerController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Volunteer;
use Illuminate\Support\Facades\Mail;
use App\Mail\VolunteerConfirmation;

class VolunteerController extends Controller
{
    public function index(Request $request)
    {
        $volunteers = Volunteer::byStatus($request->get('status'))->paginate(10)->toJson();

        return response($volunteers,200);
    }

    public function store(Request $request)
    {
        $volunteer = Volunteer::create($request->all());

        Mail::send(new VolunteerConfirmation($volunteer));

        return response()->json($volunteer, 201);
    }

    public function destroy(Volunteer $volunteer)
    {
         $volunteer->delete();
         return response()->json(null, 204);
    }
}

app/Http/Controllers/Admin/VolunteerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\VolunteerRequest;
use App\Mail\VolunteerConfirmation;
use App\Models\Volunteer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use App\Http\Controllers\Controller;

class VolunteerController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Volunteer::class, 'volunteer');
    }

    public function index(Request $request)
    {
        $status = $request->query('status');
        $filter = $request->query('filter');

        $query = Volunteer::orderBy('status', 'asc')->orderBy('reviewed_at', 'desc');

        if ($request->has('status') && $status != 'all') {
            $query->where('status', $status);
        }
        if ($request->has('filter')) {
            $query->where(function ($q) use ($filter) {
                $q->where('first_name', 'like', '%' . $filter . '%')
                    ->orWhere('last_name', 'like', '%' . $filter . '%')
                    ->orWhere('email', 'like', '%' . $filter . '%');
            });
        }
        $volunteers = $query->paginate(10)->withQueryString();

        return view('admin.volunteers.index', ['volunteers' => $volunteers, 'estado' => $status, 'filter' => $filter]);
    }

    public function create()
    {
    }

    public function store(VolunteerRequest $request)
    {
    }

    public function show(Volunteer $volunteer)
    {
        return view('admin.volunteers.show', ['volunteer' => $volunteer]);
    }

    public function edit(Volunteer $volunteer)
    {
        //
    }

    public function update(Request $request, Volunteer $volunteer)
    {
        //
    }

    public function destroy(Volunteer $volunteer)
    {
        $volunteer->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/VolunteerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\VolunteerRequest;
use App\Mail\VolunteerConfirmation;
use App\Models\Volunteer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class VolunteerController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Volunteer::class, 'volunteer');
    }

    public function index()
    {
        return view('website.volunteers.index', ['volunteers' => Volunteer::paginate(10)]);
    }

    public function create()
    {
        return view('website.volunteers.create');
    }

    public function store(VolunteerRequest $request)
    {
        $volunteer = Volunteer::create($request->all());

        Mail::send(new VolunteerConfirmation($volunteer));

        return redirect()->back()->withSuccess('Inscripto como voluntario exitosamente');
    }

    public function show(Volunteer $volunteer)
    {
        return view('website.volunteers.show', ['volunteer' => $volunteer]);
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy(Volunteer $volunteer)
    {
        // $volunteer->delete();
        // return redirect()->back();
    }
}

resources/views/admin/volunteers/index.blade.php
@extends('admin.layout')

@section('content')
    <div class="m-4">
        <h2>
            Listado de Voluntarios
        </h2>
        <form method='GET' action="{{ route('admin.volunteers.index') }}">
            <div class="form-row align-items-end">
                <div class="form-group col-md-2">
                    <label for="status">Estado:</label>
                    <select type="text" name="status" id="status" class="form-control">
                        <option {{ $estado == 'all' ? "selected" : '' }} value='all' >Todos</option>
                        <option {{ $estado == 'pending' ? "selected" : '' }} value='pending' >Pendientes</option>
                        <option {{ $estado == 'accepted' ? "selected" : '' }} value='accepted' >Aceptados</option>
                        <option {{ $estado == 'rejected' ? "selected" : '' }} value='rejected' >Rechazados</option>
                    </select>
                </div>
                <div class="form-group col-md-3">
                    <label for="filter">Buscar:</label>
                    <input type="text" name="filter" id="filter" class="form-control" value='{{ $filter? $filter : '' }}'>
                </div>
                <div class="form-group col-md-2">
                    <button type="submit" class="btn btn-primary">Filtrar</button>
                </div>
            </div>
        </form>
        <div class="table-responsive bg-light">
            <table class="table">
                <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Email</th>
                    <th>Telefono</th>
                    <th>Estado</th>
                    <th>Revision</th>
                    <th class="d-flex justify-content-center">Accion</th>
                </tr>
                </thead>
                <tbody>
                @forelse ($volunteers as $volunteer)
                    <tr>
                        <td>
                            {{$volunteer->first_name}}
                        </td>
                        <td>
                            {{$volunteer->last_name}}
                        </td>
                        <td>
                            {{$volunteer->email}}
                        </td>
                        <td>
                            {{$volunteer->phone_number}}
                        </td>
                        <td>
                        @switch($volunteer->status)
                            @case('accepted')
                                <i class="btn fas fa-check text-success" aria-hidden="true"></i>
                                @break

                            @case('rejected')
                                <i class="btn fas fa-times text-danger" aria-hidden="true"></i>
                                @break

                            @default
                            <i class="btn fas fa-question text-warning" aria-hidden="true"></i>
                        @endswitch
                        </td>
                        <td>
                            {{\Carbon\Carbon::now()->toDateString($volunteer->reviewed_at)}}
                        </td>
                        <td class="d-flex justify-content-center">
                            @unless ( $volunteer->status === 'accepted')
                            <form method='POST' action="{{ route('admin.volunteers.approve', ['volunteer' => $volunteer]) }}">
                                @csrf
                                @method('patch')
                                <button class="btn btn-link">
                                    <i class="btn fas fa-check text-success" aria-hidden="true"></i>
                                </button>
                            </form>
                            @endunless
                            @unless ( $volunteer->status === 'rejected')
                            <form method='POST' action="{{ route('admin.volunteers.reject', ['volunteer' => $volunteer]) }}">
                                @csrf
                                @method('patch')
                                <button class="btn btn-link">
                                    <i class="btn fas fa-times text-danger" aria-hidden="true"></i>
                                </button>
                            </form>
                            @endunless
                        </td>
                        <td>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="6">No hay voluntarios con esas caracteristicas</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
        <p>{{$volunteers->links()}}</p>
    </div>
@endsection