routes/web.php
<?php

use App\Http\Controllers\CommentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('website.welcome');
})->name('welcome');


Auth::routes();

Route::get('/home', function () {
    return view('website.welcome');
})->name('home');

Route::resource('categories', App\Http\Controllers\CategoryController::class);
Route::get('categories/{category}/posts', [App\Http\Controllers\PostController::class, 'index'])->name('categories.posts.index');
Route::resource('donations', App\Http\Controllers\DonationController::class);
Route::get('posts/get-more-posts', [App\Http\Controllers\PostController::class, 'getMorePosts'])->name('get-more-posts');
Route::resource('posts', App\Http\Controllers\PostController::class);
Route::resource('posts/{post}/comments', CommentController::class);
Route::post('posts/storeimage', [App\Http\Controllers\PostController::class, 'storeImage'])->name('store.image');
Route::resource('subscribers', App\Http\Controllers\SuscriberController::class);
Route::resource('volunteers', App\Http\Controllers\VolunteerController::class);

Route::prefix('admin')->name('admin.')->middleware('auth')->group(function () {
    Route::resource('posts', App\Http\Controllers\Admin\PostController::class, [
        'except' => ['create', 'store']
    ]);

    Route::resource('subscribers', App\Http\Controllers\Admin\SubscriberController::class, [
        'except' => ['create', 'store']
    ]);

    Route::delete('subscribers/{subscriber?}', [\App\Http\Controllers\Admin\SubscriberController::class, 'destroy'])->name('subscribers.destroy');



    Route::resource('volunteers', App\Http\Controllers\Admin\VolunteerController::class, [
        'except' => ['create', 'store']
    ]);

    Route::resource('comments', App\Http\Controllers\Admin\CommentController::class, [
        'except' => ['create', 'store']
    ]);

    Route::resource('donations', App\Http\Controllers\Admin\DonationController::class, [
        'except' => ['create', 'store', 'destroy']
    ]);

    Route::resource('categories', App\Http\Controllers\Admin\CategoryController::class);

    Route::get('posts/{post}/approved', [App\Http\Controllers\Admin\PostApprovalController::class, 'publish'])->name('posts.publish');

    Route::patch('volunteers/{volunteer}/approve', [App\Http\Controllers\Admin\VolunteerApprovalController::class, 'approve'])->name('volunteers.approve');
    Route::patch('volunteers/{volunteer}/reject', [App\Http\Controllers\Admin\VolunteerApprovalController::class, 'reject'])->name('volunteers.reject');
});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use HasFactory;

    protected $fillable = [
        'email',
        'ip',
        'body',
    ];

    public function post()
    {
        return $this->belongsTo(Post::class);
    }
}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CommentRequest;
use App\Models\Comment;
use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Post $post
     * @param $post_id
     * @return \Illuminate\Http\Response
     */
    public function index(Post $post)
    {
        return view('admin.comments.index', ['comments' => Comment::paginate(10)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Post $post)
    {
        // return view('admin.comments.create', ['post' => $post]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CommentRequest $request
     * @param Post $post
     * @return \Illuminate\Http\Response
     */
    public function store(CommentRequest $request, Post $post)
    {
        // $comment = Comment::create([
        //     'email' => $request->email,
        //     'ip' => request()->ip(),
        //     'body' => $request->body,
        //     'post_id' => $post->id,
        // ]);

        // return $comment;
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post, Comment $comment)
    {
        return $comment;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $comment)
    {
        $this->authorize('update-comment', $comment);
        return view('admin.comments.edit', [
            'comment' => $comment,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function update(CommentRequest $request, Comment $comment)
    {
        $this->authorize('update-comment', $comment);
        $comment->update($request->all());
        $comment->ip = request()->ip();
        return redirect()->back()->withSuccess('Comentario editado exitosamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $this->authorize('delete-comment', $comment);
        $comment->delete();
        return back()->withSuccess('Comentario eliminado exitosamente');
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CommentRequest;
use App\Models\Comment;
use App\Models\Post;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Post $post
     * @param $post_id
     * @return \Illuminate\Http\Response
     */
    public function index(Post $post)
    {
        return response()->json($post->comments);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Post $post)
    {
        return view('website.comments.create', ['post' => $post]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CommentRequest $request
     * @param Post $post
     * @return \Illuminate\Http\Response
     */
    public function store(CommentRequest $request, Post $post)
    {
        $post->comments()->create([
            'email' => $request->input('email'),
            'ip' => $request->ip(),
            'body' => $request->input('body'),
        ]);

        return redirect()->route('posts.show', $post->id);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post, Comment $comment)
    {
        return $comment;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post, Comment $comment)
    {
        $this->authorize('update-comment', $comment);

        return view('website.comments.edit', [
            'post' => $post,
            'comment' => $comment,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post, Comment $comment)
    {
        $this->authorize('update-comment', $comment);

        $comment->update(
            $request->merge(['ip' => $request->ip()])
        );

        return $comment;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $this->authorize('delete-comment', $comment);

        $comment->delete();

        return back();
    }
}

resources/views/admin/comments/edit.blade.php
@extends('admin.layout')
@section('content')
<div class="m-4">
        <!-- Back to index button -->
        <a href="{{ route('admin.comments.index') }}" class="btn btn-dark p-1 mb-2"><i class="fa fa-arrow-left"></i></a>

        <header>
            <h5 class="mt-3 mb-3">Editar comentario</h5>
        </header>

        <!-- Success message -->
        @if(session('success'))
                <div class="alert alert-success mb-3 small"> {{ session('success') }}</div>
        @endif

        <form method='POST' action="{{ route('admin.comments.update', ['comment' => $comment]) }}" >
            @method('PATCH')
            @csrf

            <!-- Email input -->
            <div class="form-group">
                <label for="name">Email</label>
                <input type="text" class="form-control" id="email" name="email" placeholder="Nombre" value="{{ $comment->email }}">
                
                @error('email')
                    <div class="alert alert-danger mt-3 small p-2"> {{ $errors->first('email') }} </div>
                @enderror
            </div>

            <!-- Body input -->
            <div class="form-group">
                <label for="name">Comentario</label>
                <textarea class="form-control" id="body" name="body"> {{ $comment->body }} </textarea>
                
                @error('body')
                    <div class="alert alert-danger mt-3 small p-2"> {{ $errors->first('body') }} </div>
                @enderror
            </div>

            <button type="submit" class="btn btn-primary">Editar</button>
        </form>
    </div>
@endsection

resources/views/admin/comments/index.blade.php
@extends('admin.layout')

@section('content')
    <div class="m-4">
        <h2>
            Listado de Comentarios
        </h2>

        <!-- Success message -->
        @if(session('success'))
            <div class="alert alert-success mb-3 small"> {{ session('success') }}</div>
        @endif

        <div class="table-responsive bg-light">
            <table class="table">
                <thead>
                <tr>
                    <th>Email</th>
                    <th>Comentario</th>
                    <th>Post Id</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($comments as $comment)
                    <tr>
                        <td>
                            {{$comment->email}}
                        </td>
                        <td>
                            {{$comment->body}}
                        </td>
                        <td>
                            <a href="{{route('admin.posts.show',['post' => $comment->post_id])}}">
                                {{$comment->post_id}}
                            </a>
                        </td>
                        <td>
                            <a href="{{route('admin.comments.edit', $comment) }}">
                                <i class="btn btn-primary fas fa-edit" aria-hidden="true"></i>
                            </a>
                            <form class="d-inline-flex" action="{{route('admin.comments.destroy', ['post'=>$comment->post_id, 'comment'=>$comment])}}" method="POST">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger"><i class="far fa-trash-alt"></i>
                                </button>
                            </form>
                        </td>
                        <td>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <p>{{$comments->links()}}</p>
    </div>
@endsection