routes/web.php
<?php

use App\Http\Controllers\CommentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('website.welcome');
})->name('welcome');


Auth::routes();

Route::get('/home', function () {
    return view('website.welcome');
})->name('home');

Route::resource('categories', App\Http\Controllers\CategoryController::class);
Route::get('categories/{category}/posts', [App\Http\Controllers\PostController::class, 'index'])->name('categories.posts.index');
Route::resource('donations', App\Http\Controllers\DonationController::class);
Route::get('posts/get-more-posts', [App\Http\Controllers\PostController::class, 'getMorePosts'])->name('get-more-posts');
Route::resource('posts', App\Http\Controllers\PostController::class);
Route::resource('posts/{post}/comments', CommentController::class);
Route::post('posts/storeimage', [App\Http\Controllers\PostController::class, 'storeImage'])->name('store.image');
Route::resource('subscribers', App\Http\Controllers\SuscriberController::class);
Route::resource('volunteers', App\Http\Controllers\VolunteerController::class);

Route::prefix('admin')->name('admin.')->middleware('auth')->group(function () {
    Route::resource('posts', App\Http\Controllers\Admin\PostController::class, [
        'except' => ['create', 'store']
    ]);

    Route::resource('subscribers', App\Http\Controllers\Admin\SubscriberController::class, [
        'except' => ['create', 'store']
    ]);

    Route::delete('subscribers/{subscriber?}', [\App\Http\Controllers\Admin\SubscriberController::class, 'destroy'])->name('subscribers.destroy');



    Route::resource('volunteers', App\Http\Controllers\Admin\VolunteerController::class, [
        'except' => ['create', 'store']
    ]);

    Route::resource('comments', App\Http\Controllers\Admin\CommentController::class, [
        'except' => ['create', 'store']
    ]);

    Route::resource('donations', App\Http\Controllers\Admin\DonationController::class, [
        'except' => ['create', 'store', 'destroy']
    ]);

    Route::resource('categories', App\Http\Controllers\Admin\CategoryController::class);

    Route::get('posts/{post}/approved', [App\Http\Controllers\Admin\PostApprovalController::class, 'publish'])->name('posts.publish');

    Route::patch('volunteers/{volunteer}/approve', [App\Http\Controllers\Admin\VolunteerApprovalController::class, 'approve'])->name('volunteers.approve');
    Route::patch('volunteers/{volunteer}/reject', [App\Http\Controllers\Admin\VolunteerApprovalController::class, 'reject'])->name('volunteers.reject');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/API/CategoryController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::orderBy('name', 'ASC')->get();

        return response($categories,200);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::with('posts')->orderBy('name', 'ASC')->get();
        return response()->json($categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        Category::create($request->all());
        return response()->json([
            'data' => 'Categoría creada'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Category $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return response()->json($category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Category $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', ['category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Category $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $category->update($request->all());

        return response()->json([
            'data' => 'Categoría editada'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Category $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        Post::where('category_id', $category->id)->delete();

        $category->delete();

        return response()->json([
            'data' => 'Categoría eliminada'
        ]);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Category::class, 'category');
    }

    public function index()
    {
        $categories = Category::withCount('posts')->orderBy('name', 'ASC')->get();
        return view('website.categories.index', ['categories' => $categories]);
    }

    public function create()
    {
        //
    }

    public function store(CategoryRequest $request)
    {
        //
    }

    public function show(Category $category)
    {
        //
    }

    public function edit(Category $category)
    {
        //
    }

    public function update(CategoryRequest $request, Category $category)
    {
        //
    }

    public function destroy(Category $category)
    {
        //
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layout')
@section('content')
<div class="container">
    <div class="d-flex justify-content-center my-4 py-4">
        <div class="col-xs-12 col-sm-10 col-md-10 col-lg-8 col-xl-6">
            <form action="{{ route('admin.categories.store') }}" method="POST">
                @csrf

                <div class="form-group">
                    <label for="name">Nombre de categoría</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Nombre" value="{{ old('name') }}">

                    @error('name')
                    <div class="error"> {{ $errors->first('name') }} </div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Ingresar</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layout')

@section('title', 'Editar categoría')

@section('content')
    <div class="m-4">
        <!-- Back to index button -->
        <a href="{{ route('admin.categories.index') }}" class="btn btn-dark p-1 mb-2"><i class="fa fa-arrow-left"></i></a>

        <header>
            <h5 class="mt-3 mb-3">Editar categoría</h5>
        </header>

        <!-- Success message -->
        @if(session('success'))
                <div class="alert alert-success mb-3 small"> {{ session('success') }}</div>
        @endif

        <form method='POST' action="{{ route('admin.categories.update', ['category' => $category]) }}" >
            @method('PATCH')
            @csrf

            <!-- Name input -->
            <div class="form-group">
                <label for="name">Nombre de categoría</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Nombre" value="{{ $category->name }}">
                
                @error('name')
                    <div class="alert alert-danger mt-3 small p-2"> {{ $errors->first('name') }} </div>
                @enderror
            </div>

            <button type="submit" class="btn btn-primary">Editar</button>
        </form>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layout')

@section('title', 'Categorías')

@section('content')
    <div class="m-4">
        <h2 class="mt-3 mb-3">Listado de Categorías</h2>

        <!-- Success message -->
        @if(session('success'))
                <div class="alert alert-success mb-3 small"> {{ session('success') }}</div>
        @endif

        <!-- Create category button -->
        <a class="btn btn-secondary btn-lg btn-block p-1" href="{{ route('admin.categories.create') }}" role="button">Crear categoría</a>
        
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Cantidad de posts</th>
                    <th scope="col">Editar</th>
                    <th scope="col">Borrar</th>
                </tr>
            </thead>
            <tbody>
                <!-- Rows -->
                @foreach($categories as $category)
                    <tr>
                        <!-- Name -->
                        <th scope="row">
                            <a href="{{ route('admin.categories.show', $category->id) }}">
                                {{ $category->name }}
                            </a>
                        </th>

                        <!-- Posts count -->
                        <td>
                            <a href="{{ route('admin.categories.show', $category->id) }}">
                                {{ $category->posts_count }}
                            </a>
                        </td>

                        <!-- Edit button -->
                        <td>
                        <a href="{{ route('admin.categories.edit', $category->id) }}"><i class="btn btn-primary fas fa-edit" aria-hidden="true"></i></a>
                        </td>

                        <!-- Delete button -->
                        <td>
                            <form method="POST" action="{{ route('admin.categories.destroy', $category->id) }}">                    
                                @METHOD('delete')
                                @csrf
                                <button type="submit" class="btn btn-danger" 
                                    @if($category->posts_count == 0)
                                        onclick="return confirm('Esta acción borrará la categoría {{ $category->name }}, ¿está seguro?')"
                                    @else
                                        onclick="return confirm('ALERTA: esta acción borrará la categoría {{ $category->name }} y los {{ $category-> posts_count}} posts que están relacionados, ¿está seguro?')"
                                    @endif
                                >
                                    <i class="fa fa-trash"></i> 
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <!-- Pagination buttons -->
        <div class="d-flex mb-4">
                {{ $categories->links('pagination::bootstrap-4') }}
        </div>
    </div>
@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.layout')

@section('title', $category->name)

@section('content')
   <div class="container">
        
        <div class="row ml-2 mt-4">
            <!-- Back to index button -->
            <a href="{{ route('admin.categories.index') }}" class="btn btn-dark p-1 mb-2"><i class="fa fa-arrow-left"></i></a>
        </div>
        <div class="row ml-2">
           <header><h5 class="mt-3 mb-3"> {{ $category->name }}</h5></header>
        </div>
        <div class="row">
            @forelse($category->posts as $post)
                <div class="card col-xl-6 border-0 mb-5 pr-5 pl-5">
                    <div class="card-body">
                        <!-- Photo -->
                        <a href="{{ route('posts.show', $post->id) }}">
                            <img src="{{ $post->photo }}" class="card-img-top mb-3">
                        </a>
                        <!-- Title -->
                        <a href="{{ route('posts.show', $post->id) }}" class="text-decoration-none">
                            <h5 class="card-title"> {{ $post->title }}</h5>
                        </a>
                        <div class="d-flex justify-content-between mt-2 mb-2">
                            <!-- Date -->
                            <div class="text-uppercase text-muted font-monospace">
                                {{ $post->created_at->format('d M Y') }}
                            </div>
                            <!-- Category -->
                            <div class="text-capitalize text-muted">
                                {{ $post->category->name }}
                            </div>
                        </div>
                        <!-- Author -->
                        <p class="card-text text-muted fw-bold"> {{ $post->user->first_name }} {{ $post->user->last_name }}</p>
                    </div>
                </div>
            @empty
                <div class="ml-4 mt-2 mb-4"> <p class="text-muted">Todavía no hay posts dentro de esta categoria</p></div>
            @endforelse
        </div>
    </div>
@endsection